language: go

go:
  - master

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v ./...
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - ginkgo -r -coverprofile=coverage.txt --randomizeAllSpecs --randomizeSuites --failOnPending  --trace --race --compilers=2

after_success:
  - bash <(curl -s https://codecov.io/bash)